'''
pysplat is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

pysplat is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with kicad-footprint-generator. If not, see < http://www.gnu.org/licenses/ >.

(C) 2016 by Thomas Pointhuber, <thomas.pointhuber@gmx.at>
'''

def parse_geo_file(geo_file):
    '''
    FILENAME	../rendered/tx_coverage_oe5xgl.ppm
    #		X	Y	Long		Lat
    TIEPOINT	0	0	12.000		48.999
    TIEPOINT	3599	3599	15.000		46.000
    IMAGESIZE	3600	3600
    #
    # Auto Generated by SPLAT! v1.4.2
    #
    '''

    imagesize = [0, 0]
    lat_start = 0
    lon_start = 0
    lat_end = 0
    lon_end = 0

    file = open(geo_file, "r")

    for line in file.readlines():
        line = line.rstrip('\n')

        if line.startswith('#'):
            continue  # comment

        if line.startswith('FILENAME'):
            continue  # not important for us yet

        line_parts = line.split('\t')

        if '' in line_parts:
            line_parts.remove('')

        if line.startswith('TIEPOINT'):
            if line_parts[1] == '0':
                lat_start = float(line_parts[4])
                lon_start = float(line_parts[3])
            else:
                lat_end = float(line_parts[4])
                lon_end = float(line_parts[3])

        if line.startswith('IMAGESIZE'):
            imagesize = [int(line_parts[2]), int(line_parts[1])]

    bb = [[lat_start, lon_start], [lat_end, lon_end]]

    return {"bb": bb, "imagesize": imagesize}